name: Build, Test, Pack, and Push
on: 
  push:
    branches: [ main ]

env:
  PROJECT: Devantler.KindCLI/Devantler.KindCLI.csproj
  TEST_PROJECT: Devantler.KindCLI.Tests/Devantler.KindCLI.Tests.csproj
  NUGET_PACKAGE: Devantler.KindCLI/bin/Release/Devantler.KindCLI.*.nupkg

jobs:
  build-and-test:
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        dotnet-version: ["6.0.x"]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Setup .NET SDK v${{ matrix.dotnet-version }}
        uses: actions/setup-dotnet@v3.0.0
        with:
          dotnet-version: ${{ matrix.dotnet-version }}
      - name: Restore
        run: dotnet restore $PROJECT
      - name: Build
        run: dotnet build --configuration Release --no-restore $PROJECT
      - name: Test
        run: dotnet test --configuration Release --no-restore $TEST_PROJECT
      - name: Pack
        run: dotnet pack --configuration Release --no-build $PROJECT
      - name: Push
        run: dotnet nuget push $NUGET_PACKAGE --api-key ${{ secrets.GITHUB_TOKEN }} --source "github"